### PR TITLE
Fix/infinite query hydration 8825

### LINKED ISSUE #8825: Next.js: exception encountered in prefetchInfiniteQuery causes useSuspenseInfiniteQuery to fail
### Describe the bug

I believe there is some weird behaviour when a `prefetchInfiniteQuery` fails in a server component and `useSuspenseInfiniteQuery` retries to fetch the data on the client. The exception thrown is: `Uncaught TypeError: Cannot read properties of undefined (reading 'length')`. I have spent some time debugging into this, it feels like after the failure on the server, the client retries to fetch the data and upon a successful response, it doesn't modify the response to be in the expected `{pages: [], pageParams:[]}` format, but treats it like a normal query response.

I have also noticed that query options passed are ignored (such as retry: 0).

### Your minimal, reproducible example

https://codesandbox.io/p/devbox/9lyl7g

### Steps to reproduce

The sandbox has an API endpoint that is setup to fail randomly. Verify that the hardcoded endpoint path is correct in `pokemon.ts`.

1. Restart sandbox browser until prefetch has failed
2. Observe an exception being thrown when a retry to /api request succeeds

### Expected behavior

I expect it to work fine.

### How often does this bug happen?

None

### Screenshots or Videos

_No response_

### Platform

- OS: MacOS
- Chrome
- Dependencies:

"next": "14.2.15",
"react": "18.3.1",
"react-dom": "18.3.1"

### Tanstack Query adapter

None

### TanStack Query version

5.62.7

### TypeScript version

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chosule**
Fixes #8825

> **Note**: This solution was discussed and approved by @TkDodo in [Discussion #10027](https://github.com/TanStack/query/discussions/10027)

## Problem
When `prefetchInfiniteQuery` fails on the server, `useSuspenseInfiniteQuery` on the client doesn't return the correct infinite query structure (`{ pages: [], pageParams: [] }`), causing a runtime error when accessing `data.pages`:
```
TypeError: Cannot read properties of undefined (reading 'length')
```

## Root Cause
Infinite query behavior information gets lost during hydration:

1. `infiniteQueryBehavior` is attached when `prefetchInfiniteQuery` runs on the server
2. This behavior info isn't preserved during dehydration
3. On the client, it gets restored as a regular query during hydration
4. Error occurs when data is accessed before `InfiniteQueryObserver` attaches the behavior

## Solution
Set up infinite query behavior at hydration time to guarantee correct data structure for both success and failure cases.

### 1. Added `queryType` field to `DehydratedQuery`
- Metadata to identify infinite queries
- Stores `'query' | 'infiniteQuery'` value

### 2. Auto-detect query type during dehydration
- Checks for `initialPageParam` presence to identify infinite queries
- Stores result in `queryType` field

### 3. Auto-configure behavior during hydration
- Attaches `infiniteQueryBehavior` when `queryType` is `'infiniteQuery'`

### 4. Handle failed promises
- Rejected promises aren't passed as `initialPromise`
- Allows automatic retry on the client

## Modified Files
1. `packages/query-core/src/hydration.ts`
2. `packages/query-core/src/__tests__/hydration.test.tsx`

## Tests 

**All 35 tests passing** (including 2 new tests)

New tests added:
- `should preserve queryType for infinite queries during hydration`
- `should attach infiniteQueryBehavior during hydration`

## Checklist
- [x] Added `queryType: 'query' | 'infiniteQuery'` field to `DehydratedQuery`
- [x] Auto-detect infinite queries during dehydration by checking `initialPageParam`
- [x] Auto-configure `infiniteQueryBehavior` for infinite queries during hydration
- [x] Added test cases for hydrated infinite query behavior
- [x] Guarantee correct data structure for both success and failure cases

## Summary by CodeRabbit

* **Bug Fixes**
  * Preserve infinite-query pagination and behavior during SSR hydration so hydrated clients retain pages, cursors, and correct subsequent fetch behavior.

* **Tests**
  * Added hydration tests to validate infinite query preservation, restoration, and post-hydration fetching.

* **Chores**
  * Added release metadata documenting this patch release.

### CODE REVIEW

File: packages/query-core/src/hydration.ts [hunk 1]
```diff
@@ -239,16 +255,21 @@ export function hydrate(
           })
         }
       } else {
+        const queryOptions: any = {
+          ...client.getDefaultOptions().hydrate?.queries,
+          ...options?.defaultOptions?.queries,
+          queryKey,
+          queryHash,
+          meta,
+        }
```
Comment (TkDodo) [inline packages/query-core/src/hydration.ts]: can we keep this inlined please and just conditionally assign `behavior`:

```
behavior: queryType === 'infiniteQuery'
  ? (infiniteQueryBehavior() as QueryBehavior<unknown, unknown, unknown>)
  : undefined,
```

File: packages/query-core/src/hydration.ts [hunk 2]
```diff
@@ -272,13 +293,24 @@ export function hydrate(
...
+        if (!isRejectedThenable) {
+          query
+            .fetch(undefined, {
+              // RSC transformed promises are not thenable
+              initialPromise: Promise.resolve(promise).then((resolvedData) => {
+                return deserializeData(resolvedData)
+              }),
+            })
+            // Avoid unhandled promise rejections
+            .catch(noop)
```
Comment (TkDodo) [inline packages/query-core/src/hydration.ts]: I don’t understand what this change has to do with infinite queries ?

Comment (chosule) [reply packages/query-core/src/hydration.ts]: @TkDodo  
Applied your feedback! 🙏

You're right that the rejected promise handling wasn't directly related to #8825. 
I've removed that part and inlined the behavior assignment as suggested.

Please take another look when you can!

**Comment by chosule** [comment]
Hi @TkDodo, gentle ping! Let me know if there's anything else to address.

File: packages/query-core/src/hydration.ts [hunk 3]
```diff
@@ -70,6 +72,11 @@ function dehydrateMutation(mutation: Mutation): DehydratedMutation {
   }
 }
 
+function isInfiniteQuery(query: Query): boolean {
+  const options = query.options as any
```
Comment (TkDodo) [inline packages/query-core/src/hydration.ts]: the `as any` seems super unnecessary


```suggestion
  const options = query.options
```

File: packages/query-core/src/hydration.ts (hunk 1 above)
Comment (TkDodo) [reply packages/query-core/src/hydration.ts]: this is still not addressed

Comment (chosule) [reply packages/query-core/src/hydration.ts]: Removed `any` from `queryOptions` and changed the cast to `QueryBehavior<unknown, DefaultError, unknown>`. 
Is this the direction you had in mind?

File: packages/query-core/src/hydration.ts (hunk 3 above)
Comment (chosule) [reply packages/query-core/src/hydration.ts]: Removed `as any` from `query.options`.

**Comment by TkDodo** [comment]
I had a different idea today: what if we actually store the `type` on the `Query` class? In places where we now append the `infiniteQueryBehavior`, we could instead set `type: 'infiniteQuery'`.

then, we could just attach the behavior when the queryFn is run for every query that has an infinite type.

for hydration, all we would need to do is add the `type` field to the list of fields we hydrate / dehydrate then, and it should work ootb.

what do you think?

**Comment by chosule** [comment]
> I had a different idea today: what if we actually store the `type` on the `Query` class? In places where we now append the `infiniteQueryBehavior`, we could instead set `type: 'infiniteQuery'`.
> 
> then, we could just attach the behavior when the queryFn is run for every query that has an infinite type.
> 
> for hydration, all we would need to do is add the `type` field to the list of fields we hydrate / dehydrate then, and it should work ootb.
> 
> what do you think?

Hi @TkDodo, thanks again for the suggestion — I tried your approach and refactored things a bit.
- Added type: 'query' | 'infiniteQuery' to Query
- Query.fetch() now applies infiniteQueryBehavior automatically when type === 'infiniteQuery'
- Callers now pass _type: 'infiniteQuery' as a hint instead of wiring behavior directly
- hydrate() restores that _type for infinite queries, so the type survives hydration
- Also added a regression test covering SSR -> dehydrate -> hydrate -> refetch
