### PR TITLE
fix(react-query): eslint-plugin-query now working with vanilla js

### LINKED ISSUE #8257: eslint-plugin-query not working with vanilla JS
### Describe the bug

Seems like eslint-plugin-query is not working with vanilla JS apps.

Did some digging and it seems like in  `/utils/detect-react-query-imports.ts` -> `detectionInstructions` it specifically wants `node.importKind === 'value'` but from my research this is only set for TS. In JS it's undefined. ([link to src](https://github.com/TanStack/query/blob/b8bef6a5c82863c3e186cf7577aabd05796c3215/packages/eslint-plugin-query/src/utils/detect-react-query-imports.ts#L58))

### Your minimal, reproducible example

https://stackblitz.com/edit/react-query-lint

### Steps to reproduce

run `npm run lint` in console (it should also run automatically when link is opened)

### Expected behavior

detect "@tanstack/query/stable-query-client" and "@tanstack/query/no-rest-destructuring" errors

### How often does this bug happen?

Every time

### Screenshots or Videos

_No response_

### Platform

stackblitz

### Tanstack Query adapter

react-query

### TanStack Query version

5.59.19

### TypeScript version

no typescript

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ShyneADL**
To fix the issue with detecting imports in both TypeScript and JavaScript files, I modify the `ImportDeclaration` handler to handle cases where `importKind` might be undefined.

The key change is adding `node.importKind === undefined` to the condition. This ensures the import detection works for both TypeScript (where` importKind` is explicitly 'value') and JavaScript (where `importKind` is undefined).

This modification should resolve the lint plugin's compatibility issue with vanilla JavaScript apps by allowing import detection regardless of the `importKind` value.

closes #8257

### CODE REVIEW

File: packages/eslint-plugin-query/src/utils/detect-react-query-imports.ts [hunk 1]
```diff
@@ -55,7 +55,8 @@ export function detectTanstackQueryImports(create: EnhancedCreate): Create {
       ImportDeclaration(node) {
         if (
           node.specifiers.length > 0 &&
-          node.importKind === 'value' &&
+          // Change condition to check for undefined or 'value'
+          (node.importKind === 'value' || node.importKind === undefined) &&
```
Comment (TkDodo) [inline packages/eslint-plugin-query/src/utils/detect-react-query-imports.ts:59]: the comment is pretty unnecessary:

```suggestion
          (node.importKind === 'value' || node.importKind === undefined) &&
```

**Review by TkDodo — APPROVED** [review]

**Comment by TkDodo** [comment]
there’s a lint error because typescript thinks the check is unnecessary:

```
/home/workflows/workspace/packages/eslint-plugin-query/src/utils/detect-react-query-imports.ts
  58:43  error  Unnecessary conditional, both sides of the expression are literal values  @typescript-eslint/no-unnecessary-condition
```

you must likely disable the linter for this line

**Comment by ShyneADL** [comment]
Hey, just here to bring attention back to this PR

I want to ask if there's any reason why it hasn't been merged yet?
Thanks
